# Configuration for the plugin #
config:
  # This sends information that is util to me(mainly to see quantity of people using it). It's not necessary for the plugin, but it helps to maintain me motivated. #
  # true/false #
  enabled_metrics: true
  gui:
    title: "&7Enchanting Menu"
    empty-slot: "BLACK_STAINED_GLASS_PANE"
    # Leave them empty if you don't want any sound #
    # Volume goes from 0.1 to 1.0 #
    sound-on-open: "BLOCK_CHEST_OPEN"
    volume-on-open: 0.5
    sound-on-close: "BLOCK_CHEST_CLOSE"
    volume-on-close: 0.5
  enchantments:
    replenish:
      name: "Replenish"
      lore-name: "&7Replenish I"
      # Leave it empty if you don't want any sound #
      # Volume goes from 0.1 to 1.0 #
      sound-on-break: "BLOCK_COMPOSTER_READY"
      volume-on-break: 0.5
    farmers-grace:
      name: "Farmer's Grace"
      lore-name: "&7Farmer's Grace I"
    delicate:
      name: "Delicate"
      lore-name: "&7Delicate I"
    farmers-step:
      name: "Farmer's Step"
      lore-name1: "&7Farmer's Step I"
      lore-name2: "&7Farmer's Step II"
      lore-name3: "&7Farmer's Step III"
    grand-tilling:
      name: "Grand Tilling"
      lore-name1: "&7Grand Tilling I"
      lore-name2: "&7Grand Tilling II"
      lore-name3: "&7Grand Tilling III"


# Messages for the plugin #
messages:
  no-permission-command: "&cYou don't have permissions to use this command."
  no-permission-action: "&cYou don't have permissions to perform this action."
  reloaded-config: "&aConfig reloaded successfully."