# Support: https://discord.gg/TrNpu3dacW
# GitHub: https://github.com/Manuton04/FarmingPlus
#
# Developers: Manuton
# GitHub: https://github.com/Manuton04
#
# Configuration for the plugin #
config:
  # This sends anonymous statistics that helps me improve the plugin. It's not necessary, but it helps to maintain me motivated. #
  enabled_metrics: true
  # This is the prefix that will be shown in the messages #
  prefix: "&6&l[&2&lFarmingPlus&6&l] "
  gui:
    title: "&7Enchanting Menu"
    empty-slot: "BLACK_STAINED_GLASS_PANE"
    # Leave them empty if you don't want any sound #
    # Volume goes from 0.1 to 1.0 #
    sound-on-open: "BLOCK_CHEST_OPEN"
    volume-on-open: 0.5
    sound-on-close: "BLOCK_CHEST_CLOSE"
    volume-on-close: 0.5
  enchantments:
    replenish:
      name: "Replenish"
      lore-name: "&7Replenish I"
      # Leave it empty if you don't want any sound #
      # Volume goes from 0.1 to 1.0 #
      sound-on-break: "BLOCK_COMPOSTER_READY"
      volume-on-break: 0.5
      cost:
        # Exp in levels #
        exp: 30
        money: 10000
        items:
          - "DIAMOND 1"
          - "GOLD_INGOT 8"
    farmers-grace:
      name: "Farmer's Grace"
      lore-name: "&7Farmer's Grace I"
      cost:
        exp: 30
        money: 10000
        items:
          - "DIAMOND 1"
          - "GOLD_INGOT 8"
    delicate:
      name: "Delicate"
      lore-name: "&7Delicate I"
      cost:
        exp: 30
        money: 10000
        items:
          - "DIAMOND 1"
          - "GOLD_INGOT 8"
    irrigate:
      name: "Irrigate"
      lore-name: "&7Irrigate I"
      # Max blocks that can be irrigated at once in a row #
      # Blocks are filled with water until its max or until it reaches a block #
      max-blocks: 64
      cost:
        exp: 30
        money: 10000
        items:
          - "DIAMOND 1"
          - "GOLD_INGOT 8"
    farmers-step:
      name: "Farmer's Step"
      lore-name1: "&7Farmer's Step I"
      lore-name2: "&7Farmer's Step II"
      lore-name3: "&7Farmer's Step III"
      cost1:
        exp: 30
        money: 5000
        items:
          - "DIAMOND 1"
          - "GOLD_INGOT 8"
      cost2:
        exp: 45
        money: 10000
        items:
          - "DIAMOND 32"
      cost3:
        exp: 60
        money: 15000
        items:
          - "DIAMOND_BLOCK 8"
      # This gui opens when using LEFT click in the air with the enchanted boots #
      gui:
        title: "&7Farmer's Step Menu"
        empty-slot: "BLACK_STAINED_GLASS_PANE"
        sound-on-set: "ENTITY_EXPERIENCE_ORB_PICKUP"
        volume-on-set: 0.5
    grand-tilling:
      name: "Grand Tilling"
      lore-name1: "&7Grand Tilling I"
      lore-name2: "&7Grand Tilling II"
      lore-name3: "&7Grand Tilling III"
      cost1:
        exp: 30
        money: 5000
        items:
          - "DIAMOND 1"
          - "GOLD_INGOT 8"
      cost2:
        exp: 45
        money: 10000
        items:
          - "DIAMOND 32"
      cost3:
        exp: 60
        money: 15000
        items:
          - "DIAMOND_BLOCK 8"
      # Max blocks that can be tilled at once in a row #
      # Blocks are tilled until its max or until it reaches a block that can't be tilled #
      level3-max-blocks: 64