# Configuration for the plugin #
config:
  # This sends information that is util to me(mainly to see quantity of people using it). It's not necessary for the plugin, but it helps to maintain me motivated. #
  # true/false #
  enabled_metrics: true
  enchantments:
    replenish:
      lore-name: "&7Replenish I"
    farmers-grace:
      lore-name: "&7Farmer's Grace I"
    delicate:
      lore-name: "&7Delicate I"
    farmers-step:
      lore-name1: "&7Farmer's Step I"
      lore-name2: "&7Farmer's Step II"
      lore-name3: "&7Farmer's Step III"
    grand-tilling:
      lore-name1: "&7Grand Tilling I"
      lore-name2: "&7Grand Tilling II"
      lore-name3: "&7Grand Tilling III"


# Messages for the plugin #
messages:
  no-permission-command: "&cYou don't have permissions to use this command."
  no-permission-action: "&cYou don't have permissions to perform this action."
  reloaded-config: "&aConfig reloaded successfully."