main: fp.manuton.FarmingPlus
version: 1.1.5
name: FarmingPlus
author: Manuton
api-version: 1.13
load: POSTWORLD
softdepend:
  - [Vault]
  - [WorldGuard]
  - [MythicMobs]
  - [PlaceholderAPI]
  - [Jobs]

commands:
  farmingplus:
    description: Principal command of the plugin FarmingPlus
    aliases:
      - fp